# Generated by Django 2.1.2 on 2019-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLibro', models.CharField(max_length=50)),
                ('descripcionLibro', models.CharField(max_length=300)),
                ('fotoLibro', models.ImageField(default='./media/noname.jpg', upload_to='./media/')),
                ('estadoLibro', models.CharField(default='Seleccione', max_length=100, null=True)),
            ],
        ),
    ]
