# Generated by Django 2.1.2 on 2019-06-18 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservaLibros',
            fields=[
                ('codigoReserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLibro', models.CharField(max_length=50)),
                ('descripcionLibro', models.CharField(max_length=300)),
                ('fotoLibro', models.ImageField(default='./media/noname.jpg', upload_to='./media/')),
                ('estadoLibro', models.CharField(default='Seleccione', max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Libro')),
            ],
        ),
    ]
