# Generated by Django 2.1.2 on 2019-06-19 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_auto_20190618_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigoReserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLibro', models.CharField(blank=True, max_length=50)),
                ('descripcionLibro', models.CharField(max_length=300, null=True)),
                ('estadoLibro', models.CharField(blank=True, max_length=100)),
                ('usuario', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Libro')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservalibros',
            name='idLibro',
        ),
        migrations.DeleteModel(
            name='reservaLibros',
        ),
    ]
